# Generated by Django 2.2.13 on 2020-08-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petspecie',
            name='pet_gender',
            field=models.CharField(default='m', max_length=1),
            preserve_default=False,
        ),
    ]
