# Generated by Django 2.2.13 on 2020-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petspecie_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='kind_link',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
